version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ENV=dev
      - LOG_FILEPATH=./log/app.log
      - LOG_LEVEL=2
      - LOG_MAXSIZE=500
      - LOG_BACKUM_TERM=10
      - LOG_MAXAGE=365
      - LOG_LOCALTIME=true
      - LOG_COMPRESS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    container_name: app
    depends_on:
      - redis
    tty: true
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379